

-- !!!!!!!!!!!!!!

-- kdyz jedna vyhodila exception (tabulka neexistovala), tak uz se ostatni nesmazali a celý to prestalo fungovat - nejak se mi do toho stavu podarilo dostat
-- problem tede je kdyz nejaky existuji a nektery ne, muzes to zkusit vymyselt nejak elegantneji, tohle je hrozně naprasený

-- !!!!!!!!!!!!!!

BEGIN
     EXECUTE IMMEDIATE 'DROP TABLE Udalost_zamestnance CASCADE CONSTRAINTS PURGE';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

BEGIN
     EXECUTE IMMEDIATE 'DROP TABLE Udalost CASCADE CONSTRAINTS PURGE';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE Zamestnanec CASCADE CONSTRAINTS PURGE';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE Oddeleni CASCADE CONSTRAINTS PURGE';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;


CREATE TABLE Oddeleni (
    kod_oddeleni VARCHAR(10) PRIMARY KEY,
    nazev_oddeleni VARCHAR(100) NOT NULL
);

-- muzem asi vymyselt ty specialni atributy jednotlivych rolí
CREATE TABLE Zamestnanec(
    c_zamestnance INT PRIMARY KEY,
    rodne_c       CHAR(10) NOT NULL,
    jmeno         VARCHAR(60) NOT NULL,
    prijmeni      VARCHAR(60) NOT NULL,
    role          VARCHAR(12) NOT NULL,
    id_nadrizeny_reditel INT,
    kod_oddeleni_zamestnance VARCHAR(10),
    CONSTRAINT FK_nadrizeny_reditel
        FOREIGN KEY (id_nadrizeny_reditel) REFERENCES Zamestnanec(c_zamestnance),
    CONSTRAINT FK_oddeleni_manazera
        FOREIGN KEY (kod_oddeleni_zamestnance) REFERENCES Oddeleni(kod_oddeleni),
    CONSTRAINT CHK_format_rc
        CHECK ( REGEXP_LIKE(rodne_c, '^[0-9]{9}[0-9]?$') AND MOD(rodne_c, 11) = 0),
    CONSTRAINT CHK_role_zamestnance
        CHECK ( (role = 'ředitel' AND id_nadrizeny_reditel IS NULL AND kod_oddeleni_zamestnance IS NULL) OR
                (role = 'manažer' AND id_nadrizeny_reditel IS NULL AND kod_oddeleni_zamestnance IS NOT NULL) OR
                (role = 'sekretářka' AND id_nadrizeny_reditel IS NULL AND kod_oddeleni_zamestnance IS NOT NULL) OR
                (role = 'sekretářka' AND id_nadrizeny_reditel IS NOT NULL AND kod_oddeleni_zamestnance IS NULL))
);


CREATE TABLE Udalost (
    id_udalosti INT GENERATED BY DEFAULT ON NULL AS IDENTITY,
    datum_cas_od DATE NOT NULL,
    datum_cas_do DATE NOT NULL,
    nazev VARCHAR(100) NOT NULL,
    misto_konani VARCHAR(255) NOT NULL ,
    popis VARCHAR(500),
    id_autor INT NOT NULL,
    CONSTRAINT PK_id_udalosti
        PRIMARY KEY (id_udalosti),
    CONSTRAINT FK_autor
        FOREIGN KEY (id_autor) REFERENCES Zamestnanec(c_zamestnance),
    CONSTRAINT CHK_data
        CHECK(datum_cas_od < datum_cas_do)
);

CREATE TABLE Udalost_zamestnance (
    c_zamestnance INT NOT NULL,
    id_udalosti INT NOT NULL,
    CONSTRAINT PK_udalost_zamestance
        PRIMARY KEY (c_zamestnance, id_udalosti),
    CONSTRAINT FK_zamestnanec
        FOREIGN KEY (c_zamestnance) REFERENCES Zamestnanec(c_zamestnance),
    CONSTRAINT FK_udalost
        FOREIGN KEY (id_udalosti) REFERENCES Udalost(id_udalosti)
);

INSERT INTO Oddeleni (kod_oddeleni, nazev_oddeleni)
VALUES ('FIN', 'Finanční oddělení');

INSERT INTO Oddeleni (kod_oddeleni, nazev_oddeleni)
VALUES ('HR', 'Oddělení lidských zdrojů');

INSERT INTO Zamestnanec (c_zamestnance, rodne_c, jmeno, prijmeni, role)
VALUES (1,  7902173675, 'Jan', 'Pajtl', 'ředitel');

INSERT INTO Zamestnanec (c_zamestnance, rodne_c, jmeno, prijmeni, role, kod_oddeleni_zamestnance)
VALUES (2,  8406087415, 'Petr', 'Kubala', 'manažer', 'FIN');

INSERT INTO Zamestnanec (c_zamestnance, rodne_c, jmeno, prijmeni, role, id_nadrizeny_reditel)
VALUES (3,  9258087894, 'Eva', 'Modrá', 'sekretářka', 1);

INSERT INTO Zamestnanec (c_zamestnance, rodne_c, jmeno, prijmeni, role, kod_oddeleni_zamestnance)
VALUES (4,  6553157160, 'Anna', 'Zoufalá', 'sekretářka', 'FIN');

INSERT INTO Udalost (datum_cas_od, datum_cas_do, nazev, misto_konani, popis, id_autor)
VALUES ( TO_DATE('5.4.2022 10:00', 'DD.MM.YYYY HH24:MI'), TO_DATE('5.4.2022 12:00', 'DD.MM.YYYY HH24:MI'), 'Schůzka s obchodními partnery', 'Vstupní hala', 'Každoroční setkání s obchodními partnery ze zahraniční pobočky. Dresscode: business formal',  3);

INSERT INTO Udalost (datum_cas_od, datum_cas_do, nazev, misto_konani, id_autor)
VALUES ( TO_DATE('3.4.2022 12:00', 'DD.MM.YYYY HH24:MI'), TO_DATE('3.4.2022 16:00', 'DD.MM.YYYY HH24:MI'), 'Porada ohledně marketingu', 'Konferenční sál', 4);

INSERT INTO Udalost_zamestnance (c_zamestnance, id_udalosti)
VALUES (1, 1);

INSERT INTO Udalost_zamestnance (c_zamestnance, id_udalosti)
VALUES (2, 1);

INSERT INTO Udalost_zamestnance (c_zamestnance, id_udalosti)
VALUES (2, 2);
